# https://github.com/kchaney1508
# https://webui.advntr.dev/

# Other: Reload Command Lang
reload-success-message: "<newline><red>Admin: Fendoris plugin config reloaded successfully.<reset><newline>"

# System: MOTD
server-list-motd: "<reset>                      <gold><bold>Fendoris</bold></gold><reset><newline><reset>               <gray>Currently Whitelisted</gray><reset>"
server-list-ping-logs: true # Logs server list ping requests to console

# System: Welcome / Join / Quit
private-join-message-enabled: true
public-join-message-enabled: true
public-quit-message-enabled: true

private-join-message: "<newline><color:#38aa56>Hey, %player%! Looks like you successfully connected. Please be mindful we're still in development and you may encounter server bugs. Hover <hover:show_text:'<u>fendoris.com/discord</u>'><click:open_url:'https://fendoris.com/discord'><b>here</b></click></hover> for our Discord.</color><reset> <newline><newline><gray>You are currently playing on <hover:show_text:'<u>fendoris.com/javacore</u>'><click:open_url:'https://fendoris.com/javacore'>v%version%</click></hover>.</gray><reset><newline>"
public-join-message: "<gray>%player% Connected</gray><reset>"
public-quit-message: "<gray>%player% Disconnected</gray><reset>"

# System: PvP Toggle
pvp-toggle-system-enabled: true
pvp-toggle-cooldown-enabled: true
pvp-toggle-cooldown-seconds: 30
pvp-message-cooldown-seconds: 5
pvp-toggle-combat-cooldown-enabled: true
pvp-toggle-combat-cooldown-seconds: 10

pvp-toggle-disabled-message: "<red>The PvP toggle system is currently disabled on this server.<reset>"
pvp-combat-cooldown-message-less-than-1: "<red>You must wait less than 1s after combat to toggle PvP.<reset>"
pvp-combat-cooldown-message: "<red>You must wait %seconds%s after combat to toggle PvP.<reset>"
pvp-toggle-cooldown-message-less-than-1: "<red>You must wait less than 1s to toggle PvP again.<reset>"
pvp-toggle-cooldown-message: "<red>You must wait %seconds%s to toggle PvP again.<reset>"
pvp-disabled-message: "<red>You have disabled PvP.<reset>"
pvp-enabled-message: "<red>You have enabled PvP.<reset>"
pvp-attacker-disabled-message: "<red>You cannot hit players while PvP is disabled.<reset>"
pvp-victim-disabled-message: "<red>That player has PvP disabled.<reset>"

# System: Death Messages
death-message-enabled: true
death-message-prefix: "<i>Death:"

# System: Broadcast Command use to Admins
admin-command-logs-enabled: true

admin-pvp-toggle-on: "<gray><i>[%player%: toggled their PvP on]<reset>"
admin-pvp-toggle-off: "<gray><i>[%player%: toggled their PvP off]<reset>"
admin-reload-broadcast-message: "<gray><i>[%player%: Fendoris plugin config reloaded successfully]<reset>"

# System: Tablist
tablist-enabled: true # Restart suggested
tablist-update-interval-seconds: 3 # Suggested for Performance
tablist-padding-spaces: 2 # Num of padding spaces left and right of each header/footer line

tablist-header: "<newline><gold><b>Fendoris</b></gold><reset><newline>"
tablist-footer: "<newline><gray>%online%</gray><reset><newline><gray>%ping%ms Latency</gray> <dark_gray>/</dark_gray> <gray>%tps% TPS</gray><reset><newline>"

online-count-substitutions:
  1: "One Online Player"
  2: "Two Online Players"
  3: "Three Online Players"
  4: "Four Online Players"
  5: "Five Online Players"
  6: "Six Online Players"
  7: "Seven Online Players"
  8: "Eight Online Players"
  9: "Nine Online Players"

tablist-testing-online-count: -1 # -1 or 0 to disable testing override, otherwise use a positive number

# System: Session Code
session-code-enabled: true
session-code-length: 6  # 4-32 & Restart suggested

session-code-message: "<reset><newline><reset><red>Your session code is <red><bold>%session_code%<reset><red>, reconnecting will generate another one. If you are reporting a server bug or client-sided issue, an Admin may ask for for this.<reset><reset><newline><reset>"

# System: Command Whitelist
command-whitelist-enabled: true
disallowed-command-message: "<red>Unknown or incomplete command.<reset>"

allowed-commands:
  - pvp
  - session
  - fendorisreload

# End of Config