# https://github.com/kchaney1508
# https://webui.advntr.dev/

# Join and quit message settings
private-join-message-enabled: true
public-join-message-enabled: true
public-quit-message-enabled: true

private-join-message: "Welcome %player% to the server!"
public-join-message: "%player% connected"
public-quit-message: "%player% disconnected"

# PvP toggle system settings
pvp-toggle-system-enabled: true
pvp-toggle-cooldown-enabled: true
pvp-toggle-cooldown-seconds: 30
pvp-message-cooldown-seconds: 5
pvp-toggle-combat-cooldown-enabled: true
pvp-toggle-combat-cooldown-seconds: 10

pvp-toggle-disabled-message: "The PvP toggle system is currently disabled on this server."
pvp-combat-cooldown-message-less-than-1: "You must wait less than 1s after combat to toggle PvP."
pvp-combat-cooldown-message: "You must wait %seconds%s after combat to toggle PvP."
pvp-toggle-cooldown-message-less-than-1: "You must wait less than 1s to toggle PvP again."
pvp-toggle-cooldown-message: "You must wait %seconds%s to toggle PvP again."
pvp-disabled-message: "You have disabled PvP."
pvp-enabled-message: "You have enabled PvP."
pvp-attacker-disabled-message: "You cannot hit players while PvP is disabled."
pvp-victim-disabled-message: "That player has PvP disabled."

# Death message settings
death-message-enabled: true
death-message-prefix: "Death:"

