# https://github.com/kchaney1508
# https://webui.advntr.dev/

reload:
  no-permission: "<red>You don't have permission to reload the plugin.</red>"
  reload-success: "<newline><gold>Operator: Fendoris plugin config reloaded successfully.<reset><newline>"
  reload-broadcast: "<gray>[<gold>Operator</gold>: <white>%player%</white> reloaded the plugin]</gray>"

# System: MOTD
server-list-motd: "<reset>                      <gold><bold>Fendoris</bold></gold><reset><newline><reset>               <gray>Currently Whitelisted</gray><reset>"
server-list-ping-logs: true # Logs server list ping requests to console

# System: Welcome / Join / Quit
private-join-message-enabled: true
public-join-message-enabled: true
public-quit-message-enabled: true

private-join-message: "<newline><color:#38aa56>Hey, %player%! Looks like you successfully connected. Please be mindful we're still in development and you may encounter server bugs. Hover <hover:show_text:'<u>fendoris.com/discord</u>'><click:open_url:'https://fendoris.com/discord'><b>here</b></click></hover> for our Discord.</color><reset> <newline><newline><gray>You are currently playing on <hover:show_text:'<u>fendoris.com/javacore</u>'><click:open_url:'https://fendoris.com/javacore'>v%version%</click></hover>.</gray><reset><newline>"

public-join-message: "<gray>%player% connected</gray><reset>"
public-quit-message: "<gray>%player% disconnected</gray><reset>"

public-operator-join-message: "<reset><gold><hover:show_text:\"<gold>This player is an Operator</gold>\n\n<gray>These are trusted members of our community who handle server management, maintenance and moderation. You'll only see this hover text when they join or leave the game.</gray>\">%player%</hover></gold> <gray>connected</gray><reset>"
public-operator-quit-message: "<reset><gold><hover:show_text:\"<gold>This player is an Operator</gold>\n\n<gray>These are trusted members of our community who handle server management, maintenance and moderation. You'll only see this hover text when they join or leave the game.</gray>\">%player%</hover></gold> <gray>disconnected</gray><reset>"

# System: PvP
system.pvp:
  enabled: true

  cooldown-enabled: true
  cooldown-seconds: 30

  combat-cooldown-enabled: true
  combat-cooldown-seconds: 10

  message-cooldown-seconds: 5
  attacker-disabled-message: "<red>You cannot PvP while your PvP is disabled.<reset>"
  victim-disabled-message: "<red>This player has PvP disabled.<reset>"

  only-player-message: "<red>Only players can use this command.<reset>"
  usage-message: "<red>Usage: /pvp (Toggle PvP on or off for yourself)<reset>"
  toggle-disabled-message: "<red>The PvP toggle system is currently disabled on this server.<reset>"
  combat-cooldown-message-less-than-1: "<red>You must wait less than 1s after combat to toggle PvP.<reset>"
  combat-cooldown-message: "<red>You must wait %seconds%s after combat to toggle PvP.<reset>"
  toggle-cooldown-message-less-than-1: "<red>You must wait less than 1s to toggle PvP again.<reset>"
  toggle-cooldown-message: "<red>You must wait %seconds%s to toggle PvP again.<reset>"
  disabled-message: "<red>You have disabled PvP.<reset>"
  enabled-message: "<red>You have enabled PvP.<reset>"
  operator-pvp-toggle-off: "<gray>[<red>Player</red>: <white>%player%</white> toggled their PvP <red>off</red>]</gray>"
  operator-pvp-toggle-on: "<gray>[<red>Player</red>: <white>%player%</white> toggled their PvP <green>on</green>]</gray>"

# System: Death Messages
death-message-enabled: true
death-message-prefix: "<i>Death:"

# System: Broadcast Command use to Operators
operator-command-logs-enabled: true

operator-pvp-toggle-on: "<gray><i>[%player%: toggled their PvP on]<reset>"
operator-pvp-toggle-off: "<gray><i>[%player%: toggled their PvP off]<reset>"
operator-reload-broadcast-message: "<gray><i>[%player%: Fendoris plugin config reloaded successfully]<reset>"

# System: Tablist
tablist-enabled: true # Restart suggested
tablist-update-interval-seconds: 3 # Suggested for Performance
tablist-padding-spaces: 2 # Num of padding spaces left and right of each header/footer line

tablist-header: "<newline><gold><b>Fendoris</b></gold><reset><newline>"
tablist-footer: "<newline><gray>%online%</gray><reset><newline><gray>%ping%ms Latency</gray> <dark_gray>/</dark_gray> <gray>%tps% TPS</gray><reset><newline>"

tab-operator-color: gold # black, dark_blue, dark_green, dark_aqua, dark_red, dark_purple, gold, gray, dark_gray, blue, green, aqua, red, light_purple, yellow, white

online-count-substitutions:
  1: "One Online Player"
  2: "Two Online Players"
  3: "Three Online Players"
  4: "Four Online Players"
  5: "Five Online Players"
  6: "Six Online Players"
  7: "Seven Online Players"
  8: "Eight Online Players"
  9: "Nine Online Players"

tablist-testing-online-count: -1 # -1 or 0 to disable testing override, otherwise use a positive number

# System: Session Code
session:
  enabled: true
  code-length: 6  # 4-32 & Restart suggested

  only-player-message: "<red>Only players can use this command.<reset>"
  usage-message: "<red>Usage: /session (Shows your current Session Code)<reset>"
  disabled-message: "<red>The Session Code system is currently disabled.<reset>"
  code-message: "<reset><newline><reset><red>Your session code is <click:suggest_command:'%session_code%'><red><bold>%session_code%</bold><red></click>, reconnecting will generate another one. If you are reporting a server bug or client-sided issue, an Operator may ask for for this.<reset><reset><newline><reset>"

# System: Command Whitelist
command-whitelist-enabled: true
disallowed-command-message: "<red>Unknown or incomplete command.<reset>"

# system: Spawn, SetSpawn, SendToSpawn
spawn:
  enabled: true

  location-world: "world"
  location-x: 0.5
  location-y: 100.0
  location-z: 0.5
  location-yaw: 0.0
  location-pitch: 0.0

  cooldown: 3
  cooldown-message: "<red>You must wait %seconds%s before using this again.<reset>"
  cooldown-message-less-than-1: "<red>You must wait less than 1s to use /spawn again.<reset>"

  teleport-delay-seconds: 5
  teleport-delay-start-message: "<yellow>Teleporting to spawn in %seconds%s... Don't move!<reset>"
  teleport-cancelled-message: "<red>Teleport cancelled because you moved.<reset>"

  teleport-particles-enabled: true
  teleport-particle-name: "minecraft:portal"
  teleport-particle-count: 20

  teleport-sound-enabled: true
  teleport-sound-name: "minecraft:block.note_block.pling"
  teleport-sound-volume: 1.0
  teleport-sound-pitch: 1.0

  only-player-message: "<red>Only players can use this command.<reset>"
  usage-message: "<red>Usage: /spawn (Teleports you to the server spawn location)<reset>"
  disabled-message: "<red>The Spawn system is currently disabled on this server.<reset>"
  teleport-success-message: "<green>You have been teleported to the server spawn.<reset>"
  teleport-already-in-progress-message: "<red>You are already teleporting to spawn!<reset>"

  no-permission-message: "<red>You don't have permission to use this command.<reset>"
  sendtospawn-usage: "<red>Usage: /sendtospawn <player><reset>"
  player-not-online: "<red>That player is not online.<reset>"
  sent-to-spawn-message: "<green>You have been sent to spawn by an operator.<reset>"
  operator-sent-message: "<green>Sent %player% to spawn.<reset>"

  set-success: "<green>Spawn location saved to config.<reset>"

allowed-commands:
  - pvp
  - session
  - spawn
  - fendorisreload


hologram:
  messages:
    no-permission: "<red>You don't have permission to use /hologram.<reset>"
    created: "<green>Created hologram <white>#%id%</white> at your location.<reset>"

# Storage
holograms: {}
next-hologram: 0 # do not touch


# End of Config