name: Build Plugin

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package

      - name: Publish Latest Build to Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Latest Commit Build"
          tag_name: latest
          prerelease: true
          files: target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
